tap "heroku/brew"
tap "codekitchen/dinghy"
tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
tap "universal-ctags/universal-ctags"
brew "asciinema"
brew "autoconf"
brew "bison@2.7"
brew "cmake"
brew "curl"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr", link: true
brew "dnsmasq", restart_service: true, link: false
brew "docker"
brew "freetype"
brew "fzf"
brew "gettext"
brew "git"
brew "git-lfs"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "gpg-agent", link: true
brew "hub"
brew "icu4c"
brew "jpeg"
brew "kubernetes-helm"
brew "libtiff"
brew "libtool"
brew "libusb-compat"
brew "libxml2"
brew "libyaml"
brew "lolcat"
brew "macvim"
brew "mariadb", restart_service: true
brew "mcrypt"
brew "mono"
brew "openssl@1.1"
brew "nginx", args: ["with-http2"], restart_service: true
brew "node"
brew "openvpn", restart_service: true
brew "phantomjs"
brew "pinentry-mac"
brew "qt", link: true
brew "qt@5.5", link: true
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "redshift", restart_service: true
brew "ripgrep"
brew "rsync"
brew "stunnel"
brew "tmate"
brew "tmux"
brew "tree"
brew "unixodbc"
brew "vim"
brew "watchman"
brew "wget"
brew "wxmac"
brew "xhyve"
brew "zlib"
brew "zsh"
brew "codekitchen/dinghy/dinghy"
brew "heroku/brew/heroku"
brew "homebrew/php/php71"
brew "homebrew/php/php71-mcrypt"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "alfred"
cask "anki"
cask "balsamiq-mockups"
cask "bartender"
cask "calibre"
cask "dash"
cask "docker"
cask "dropbox"
cask "expressions"
cask "firefox"
cask "flash-npapi"
cask "flash-player"
cask "github"
cask "gitter"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "minikube"
cask "postgres"
cask "principle"
cask "rocket"
cask "screenflow"
cask "sequel-pro"
cask "sip"
cask "sketch"
cask "sketch-toolbox"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "textual"
cask "thunderbird"
cask "transmission"
cask "transmit"
cask "caskroom/versions/firefox-developer-edition"
