tap "heroku/brew"
tap "codekitchen/dinghy"
tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
tap "universal-ctags/universal-ctags"
brew "asciinema"
brew "autoconf"
brew "bison@2.7"
brew "cmake"
brew "composer"
brew "contacts"
brew "curl"
brew "libksba"
brew "pth"
brew "dirmngr", link: true
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "freetype"
brew "fzf"
brew "geoip"
brew "gettext"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "gpg-agent", link: true
brew "hub"
brew "icu4c"
brew "jpeg"
brew "kubernetes-helm"
brew "libtiff"
brew "libtool"
brew "libusb-compat"
brew "libxml2"
brew "libyaml"
brew "lolcat"
brew "macvim"
brew "mailhog", restart_service: true
brew "mariadb", restart_service: true
brew "mcrypt"
brew "mono"
brew "msmtp"
brew "mutt"
brew "mysql-utilities"
brew "neovim"
brew "nginx", restart_service: true
brew "node", link: false
brew "zlib"
brew "notmuch"
brew "openssl@1.1"
brew "openvpn", restart_service: true
brew "phantomjs"
brew "php@7.1", restart_service: true, link: true
brew "pinentry-mac"
brew "pv"
brew "qt"
brew "qt@5.5", link: true
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "redshift", restart_service: true
brew "ripgrep"
brew "rsync"
brew "stunnel"
brew "tmate"
brew "tmux"
brew "tree"
brew "urlview"
brew "vim"
brew "watchman"
brew "wget"
brew "wp-cli", link: false
brew "wxmac"
brew "xhyve"
brew "zsh"
brew "codekitchen/dinghy/dinghy"
brew "heroku/brew/heroku"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "alfred"
cask "anki"
cask "balsamiq-mockups"
cask "bartender"
cask "calibre"
cask "dash"
cask "docker"
cask "dropbox"
cask "expressions"
cask "firefox"
cask "flash-npapi"
cask "flash-player"
cask "github"
cask "gitter"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "minikube"
cask "postgres"
cask "principle"
cask "rocket"
cask "screenflow"
cask "sequel-pro"
cask "sip"
cask "sketch"
cask "sketch-toolbox"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "textual"
cask "thunderbird"
cask "transmission"
cask "transmit"
cask "caskroom/versions/firefox-developer-edition"
