;; -*- emacs-lisp -*-

(source gnu)
(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "scss-mode")
