alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~/'
alias ls='ls -a'
alias n98='n98-magerun'
alias g='git'
alias vim='nvim'
alias vi='nvim'
alias vimdiff='nvim -d'

git() {
  if [ "$1" = commit ]; then
    shift
    set -- commit -S "$@"
  fi
  command git "$@"
}

craftinit() {
  command composer create-project nystudio107/craft "$@"
}

# hub
# brew install hub
eval "$(hub alias -s)"

alias vapor='php vendor/bin/vapor'
