if [ -n "$BASH_VERSION" ] && [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
