alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~/'
alias ls='ls -a'
alias n98='n98-magerun'
alias g='git'

git() {
  if [ "$1" = commit ]; then
    shift
    set -- commit -S "$@"
  fi
  command git "$@" 
}

# hub
# brew install hub
eval "$(hub alias -s)"
